#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbRoboMatrixUdla")]
	public partial class MERRobotDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblRobot(TblRobot instance);
    partial void UpdateTblRobot(TblRobot instance);
    partial void DeleteTblRobot(TblRobot instance);
    partial void InsertTblMinisumo(TblMinisumo instance);
    partial void UpdateTblMinisumo(TblMinisumo instance);
    partial void DeleteTblMinisumo(TblMinisumo instance);
    partial void InsertTblMegasumo(TblMegasumo instance);
    partial void UpdateTblMegasumo(TblMegasumo instance);
    partial void DeleteTblMegasumo(TblMegasumo instance);
    partial void InsertTblLegosumo(TblLegosumo instance);
    partial void UpdateTblLegosumo(TblLegosumo instance);
    partial void DeleteTblLegosumo(TblLegosumo instance);
    partial void InsertTblEquipo(TblEquipo instance);
    partial void UpdateTblEquipo(TblEquipo instance);
    partial void DeleteTblEquipo(TblEquipo instance);
    partial void InsertTblCategoria(TblCategoria instance);
    partial void UpdateTblCategoria(TblCategoria instance);
    partial void DeleteTblCategoria(TblCategoria instance);
    #endregion
		
		public MERRobotDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.dbRoboMatrixUdlaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MERRobotDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MERRobotDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MERRobotDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MERRobotDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TbSeguidorLinea> TbSeguidorLineas
		{
			get
			{
				return this.GetTable<TbSeguidorLinea>();
			}
		}
		
		public System.Data.Linq.Table<TbPuntajeSeguidorLinea> TbPuntajeSeguidorLineas
		{
			get
			{
				return this.GetTable<TbPuntajeSeguidorLinea>();
			}
		}
		
		public System.Data.Linq.Table<TbPuntajeSeguidorLego> TbPuntajeSeguidorLegos
		{
			get
			{
				return this.GetTable<TbPuntajeSeguidorLego>();
			}
		}
		
		public System.Data.Linq.Table<TblSeguidorLego> TblSeguidorLegos
		{
			get
			{
				return this.GetTable<TblSeguidorLego>();
			}
		}
		
		public System.Data.Linq.Table<TblRobot> TblRobots
		{
			get
			{
				return this.GetTable<TblRobot>();
			}
		}
		
		public System.Data.Linq.Table<TblResultadosMegasumo> TblResultadosMegasumos
		{
			get
			{
				return this.GetTable<TblResultadosMegasumo>();
			}
		}
		
		public System.Data.Linq.Table<TblResultadoMinisumo> TblResultadoMinisumos
		{
			get
			{
				return this.GetTable<TblResultadoMinisumo>();
			}
		}
		
		public System.Data.Linq.Table<TblResultadoLegosumo> TblResultadoLegosumos
		{
			get
			{
				return this.GetTable<TblResultadoLegosumo>();
			}
		}
		
		public System.Data.Linq.Table<TblPuntajeLaberinto> TblPuntajeLaberintos
		{
			get
			{
				return this.GetTable<TblPuntajeLaberinto>();
			}
		}
		
		public System.Data.Linq.Table<TblPuntajeDrone> TblPuntajeDrones
		{
			get
			{
				return this.GetTable<TblPuntajeDrone>();
			}
		}
		
		public System.Data.Linq.Table<TblMinisumo> TblMinisumos
		{
			get
			{
				return this.GetTable<TblMinisumo>();
			}
		}
		
		public System.Data.Linq.Table<TblMegasumo> TblMegasumos
		{
			get
			{
				return this.GetTable<TblMegasumo>();
			}
		}
		
		public System.Data.Linq.Table<TblLegosumo> TblLegosumos
		{
			get
			{
				return this.GetTable<TblLegosumo>();
			}
		}
		
		public System.Data.Linq.Table<TblLaberinto> TblLaberintos
		{
			get
			{
				return this.GetTable<TblLaberinto>();
			}
		}
		
		public System.Data.Linq.Table<TblEquipo> TblEquipos
		{
			get
			{
				return this.GetTable<TblEquipo>();
			}
		}
		
		public System.Data.Linq.Table<TblDrone> TblDrones
		{
			get
			{
				return this.GetTable<TblDrone>();
			}
		}
		
		public System.Data.Linq.Table<TblCategoria> TblCategorias
		{
			get
			{
				return this.GetTable<TblCategoria>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbSeguidorLinea")]
	public partial class TbSeguidorLinea
	{
		
		private int _idRobot;
		
		public TbSeguidorLinea()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbPuntajeSeguidorLinea")]
	public partial class TbPuntajeSeguidorLinea
	{
		
		private int _idRobot;
		
		private System.Nullable<decimal> _timepo1;
		
		private System.Nullable<decimal> _tiempo2;
		
		private System.Nullable<decimal> _tiempo3;
		
		public TbPuntajeSeguidorLinea()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timepo1", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> timepo1
		{
			get
			{
				return this._timepo1;
			}
			set
			{
				if ((this._timepo1 != value))
				{
					this._timepo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo2", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> tiempo2
		{
			get
			{
				return this._tiempo2;
			}
			set
			{
				if ((this._tiempo2 != value))
				{
					this._tiempo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo3", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> tiempo3
		{
			get
			{
				return this._tiempo3;
			}
			set
			{
				if ((this._tiempo3 != value))
				{
					this._tiempo3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbPuntajeSeguidorLego")]
	public partial class TbPuntajeSeguidorLego
	{
		
		private int _idRobot;
		
		private System.Nullable<decimal> _timepo1;
		
		private System.Nullable<decimal> _tiempo2;
		
		private System.Nullable<decimal> _tiempo3;
		
		public TbPuntajeSeguidorLego()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timepo1", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> timepo1
		{
			get
			{
				return this._timepo1;
			}
			set
			{
				if ((this._timepo1 != value))
				{
					this._timepo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo2", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> tiempo2
		{
			get
			{
				return this._tiempo2;
			}
			set
			{
				if ((this._tiempo2 != value))
				{
					this._tiempo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo3", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> tiempo3
		{
			get
			{
				return this._tiempo3;
			}
			set
			{
				if ((this._tiempo3 != value))
				{
					this._tiempo3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblSeguidorLego")]
	public partial class TblSeguidorLego
	{
		
		private int _idRobot;
		
		public TblSeguidorLego()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblRobot")]
	public partial class TblRobot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRobot;
		
		private string _nomRobot;
		
		private string _estadoRobot;
		
		private string _liderRobot;
		
		private int _idCategoria;
		
		private int _idEquipo;
		
		private EntitySet<TblMinisumo> _TblMinisumos;
		
		private EntitySet<TblMinisumo> _TblMinisumos1;
		
		private EntitySet<TblMegasumo> _TblMegasumos;
		
		private EntitySet<TblMegasumo> _TblMegasumos1;
		
		private EntitySet<TblLegosumo> _TblLegosumos;
		
		private EntitySet<TblLegosumo> _TblLegosumos1;
		
		private EntityRef<TblEquipo> _TblEquipo;
		
		private EntityRef<TblCategoria> _TblCategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRobotChanging(int value);
    partial void OnidRobotChanged();
    partial void OnnomRobotChanging(string value);
    partial void OnnomRobotChanged();
    partial void OnestadoRobotChanging(string value);
    partial void OnestadoRobotChanged();
    partial void OnliderRobotChanging(string value);
    partial void OnliderRobotChanged();
    partial void OnidCategoriaChanging(int value);
    partial void OnidCategoriaChanged();
    partial void OnidEquipoChanging(int value);
    partial void OnidEquipoChanged();
    #endregion
		
		public TblRobot()
		{
			this._TblMinisumos = new EntitySet<TblMinisumo>(new Action<TblMinisumo>(this.attach_TblMinisumos), new Action<TblMinisumo>(this.detach_TblMinisumos));
			this._TblMinisumos1 = new EntitySet<TblMinisumo>(new Action<TblMinisumo>(this.attach_TblMinisumos1), new Action<TblMinisumo>(this.detach_TblMinisumos1));
			this._TblMegasumos = new EntitySet<TblMegasumo>(new Action<TblMegasumo>(this.attach_TblMegasumos), new Action<TblMegasumo>(this.detach_TblMegasumos));
			this._TblMegasumos1 = new EntitySet<TblMegasumo>(new Action<TblMegasumo>(this.attach_TblMegasumos1), new Action<TblMegasumo>(this.detach_TblMegasumos1));
			this._TblLegosumos = new EntitySet<TblLegosumo>(new Action<TblLegosumo>(this.attach_TblLegosumos), new Action<TblLegosumo>(this.detach_TblLegosumos));
			this._TblLegosumos1 = new EntitySet<TblLegosumo>(new Action<TblLegosumo>(this.attach_TblLegosumos1), new Action<TblLegosumo>(this.detach_TblLegosumos1));
			this._TblEquipo = default(EntityRef<TblEquipo>);
			this._TblCategoria = default(EntityRef<TblCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this.OnidRobotChanging(value);
					this.SendPropertyChanging();
					this._idRobot = value;
					this.SendPropertyChanged("idRobot");
					this.OnidRobotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomRobot", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nomRobot
		{
			get
			{
				return this._nomRobot;
			}
			set
			{
				if ((this._nomRobot != value))
				{
					this.OnnomRobotChanging(value);
					this.SendPropertyChanging();
					this._nomRobot = value;
					this.SendPropertyChanged("nomRobot");
					this.OnnomRobotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadoRobot", DbType="Char(2)")]
		public string estadoRobot
		{
			get
			{
				return this._estadoRobot;
			}
			set
			{
				if ((this._estadoRobot != value))
				{
					this.OnestadoRobotChanging(value);
					this.SendPropertyChanging();
					this._estadoRobot = value;
					this.SendPropertyChanged("estadoRobot");
					this.OnestadoRobotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_liderRobot", DbType="VarChar(25)")]
		public string liderRobot
		{
			get
			{
				return this._liderRobot;
			}
			set
			{
				if ((this._liderRobot != value))
				{
					this.OnliderRobotChanging(value);
					this.SendPropertyChanging();
					this._liderRobot = value;
					this.SendPropertyChanged("liderRobot");
					this.OnliderRobotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCategoria", DbType="Int NOT NULL")]
		public int idCategoria
		{
			get
			{
				return this._idCategoria;
			}
			set
			{
				if ((this._idCategoria != value))
				{
					if (this._TblCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCategoriaChanging(value);
					this.SendPropertyChanging();
					this._idCategoria = value;
					this.SendPropertyChanged("idCategoria");
					this.OnidCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEquipo", DbType="Int NOT NULL")]
		public int idEquipo
		{
			get
			{
				return this._idEquipo;
			}
			set
			{
				if ((this._idEquipo != value))
				{
					if (this._TblEquipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEquipoChanging(value);
					this.SendPropertyChanging();
					this._idEquipo = value;
					this.SendPropertyChanged("idEquipo");
					this.OnidEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMinisumo", Storage="_TblMinisumos", ThisKey="idRobot", OtherKey="idRobotUno")]
		public EntitySet<TblMinisumo> TblMinisumos
		{
			get
			{
				return this._TblMinisumos;
			}
			set
			{
				this._TblMinisumos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMinisumo1", Storage="_TblMinisumos1", ThisKey="idRobot", OtherKey="idRobotDos")]
		public EntitySet<TblMinisumo> TblMinisumos1
		{
			get
			{
				return this._TblMinisumos1;
			}
			set
			{
				this._TblMinisumos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMegasumo", Storage="_TblMegasumos", ThisKey="idRobot", OtherKey="idRobotUno")]
		public EntitySet<TblMegasumo> TblMegasumos
		{
			get
			{
				return this._TblMegasumos;
			}
			set
			{
				this._TblMegasumos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMegasumo1", Storage="_TblMegasumos1", ThisKey="idRobot", OtherKey="idRobotDos")]
		public EntitySet<TblMegasumo> TblMegasumos1
		{
			get
			{
				return this._TblMegasumos1;
			}
			set
			{
				this._TblMegasumos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblLegosumo", Storage="_TblLegosumos", ThisKey="idRobot", OtherKey="idRobotUno")]
		public EntitySet<TblLegosumo> TblLegosumos
		{
			get
			{
				return this._TblLegosumos;
			}
			set
			{
				this._TblLegosumos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblLegosumo1", Storage="_TblLegosumos1", ThisKey="idRobot", OtherKey="idRobotDos")]
		public EntitySet<TblLegosumo> TblLegosumos1
		{
			get
			{
				return this._TblLegosumos1;
			}
			set
			{
				this._TblLegosumos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblEquipo_TblRobot", Storage="_TblEquipo", ThisKey="idEquipo", OtherKey="idEquipo", IsForeignKey=true)]
		public TblEquipo TblEquipo
		{
			get
			{
				return this._TblEquipo.Entity;
			}
			set
			{
				TblEquipo previousValue = this._TblEquipo.Entity;
				if (((previousValue != value) 
							|| (this._TblEquipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblEquipo.Entity = null;
						previousValue.TblRobots.Remove(this);
					}
					this._TblEquipo.Entity = value;
					if ((value != null))
					{
						value.TblRobots.Add(this);
						this._idEquipo = value.idEquipo;
					}
					else
					{
						this._idEquipo = default(int);
					}
					this.SendPropertyChanged("TblEquipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblCategoria_TblRobot", Storage="_TblCategoria", ThisKey="idCategoria", OtherKey="idCat", IsForeignKey=true)]
		public TblCategoria TblCategoria
		{
			get
			{
				return this._TblCategoria.Entity;
			}
			set
			{
				TblCategoria previousValue = this._TblCategoria.Entity;
				if (((previousValue != value) 
							|| (this._TblCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblCategoria.Entity = null;
						previousValue.TblRobots.Remove(this);
					}
					this._TblCategoria.Entity = value;
					if ((value != null))
					{
						value.TblRobots.Add(this);
						this._idCategoria = value.idCat;
					}
					else
					{
						this._idCategoria = default(int);
					}
					this.SendPropertyChanged("TblCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TblMinisumos(TblMinisumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot = this;
		}
		
		private void detach_TblMinisumos(TblMinisumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot = null;
		}
		
		private void attach_TblMinisumos1(TblMinisumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot1 = this;
		}
		
		private void detach_TblMinisumos1(TblMinisumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot1 = null;
		}
		
		private void attach_TblMegasumos(TblMegasumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot = this;
		}
		
		private void detach_TblMegasumos(TblMegasumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot = null;
		}
		
		private void attach_TblMegasumos1(TblMegasumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot1 = this;
		}
		
		private void detach_TblMegasumos1(TblMegasumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot1 = null;
		}
		
		private void attach_TblLegosumos(TblLegosumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot = this;
		}
		
		private void detach_TblLegosumos(TblLegosumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot = null;
		}
		
		private void attach_TblLegosumos1(TblLegosumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot1 = this;
		}
		
		private void detach_TblLegosumos1(TblLegosumo entity)
		{
			this.SendPropertyChanging();
			entity.TblRobot1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblResultadosMegasumo")]
	public partial class TblResultadosMegasumo
	{
		
		private int _idBatalla;
		
		private int _puntosUno;
		
		private int _puntosDos;
		
		private int _idRobotUno;
		
		private int _idRobotDos;
		
		public TblResultadosMegasumo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBatalla", DbType="Int NOT NULL")]
		public int idBatalla
		{
			get
			{
				return this._idBatalla;
			}
			set
			{
				if ((this._idBatalla != value))
				{
					this._idBatalla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntosUno", DbType="Int NOT NULL")]
		public int puntosUno
		{
			get
			{
				return this._puntosUno;
			}
			set
			{
				if ((this._puntosUno != value))
				{
					this._puntosUno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntosDos", DbType="Int NOT NULL")]
		public int puntosDos
		{
			get
			{
				return this._puntosDos;
			}
			set
			{
				if ((this._puntosDos != value))
				{
					this._puntosDos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotUno", DbType="Int NOT NULL")]
		public int idRobotUno
		{
			get
			{
				return this._idRobotUno;
			}
			set
			{
				if ((this._idRobotUno != value))
				{
					this._idRobotUno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotDos", DbType="Int NOT NULL")]
		public int idRobotDos
		{
			get
			{
				return this._idRobotDos;
			}
			set
			{
				if ((this._idRobotDos != value))
				{
					this._idRobotDos = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblResultadoMinisumo")]
	public partial class TblResultadoMinisumo
	{
		
		private int _idBatalla;
		
		private int _puntosUno;
		
		private int _puntosDos;
		
		private int _idRobotUno;
		
		private int _idRobotDos;
		
		public TblResultadoMinisumo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBatalla", DbType="Int NOT NULL")]
		public int idBatalla
		{
			get
			{
				return this._idBatalla;
			}
			set
			{
				if ((this._idBatalla != value))
				{
					this._idBatalla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntosUno", DbType="Int NOT NULL")]
		public int puntosUno
		{
			get
			{
				return this._puntosUno;
			}
			set
			{
				if ((this._puntosUno != value))
				{
					this._puntosUno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntosDos", DbType="Int NOT NULL")]
		public int puntosDos
		{
			get
			{
				return this._puntosDos;
			}
			set
			{
				if ((this._puntosDos != value))
				{
					this._puntosDos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotUno", DbType="Int NOT NULL")]
		public int idRobotUno
		{
			get
			{
				return this._idRobotUno;
			}
			set
			{
				if ((this._idRobotUno != value))
				{
					this._idRobotUno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotDos", DbType="Int NOT NULL")]
		public int idRobotDos
		{
			get
			{
				return this._idRobotDos;
			}
			set
			{
				if ((this._idRobotDos != value))
				{
					this._idRobotDos = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblResultadoLegosumo")]
	public partial class TblResultadoLegosumo
	{
		
		private int _idBatalla;
		
		private int _puntosUno;
		
		private int _puntosDos;
		
		private int _idRobotUno;
		
		private int _idRobotDos;
		
		public TblResultadoLegosumo()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBatalla", DbType="Int NOT NULL")]
		public int idBatalla
		{
			get
			{
				return this._idBatalla;
			}
			set
			{
				if ((this._idBatalla != value))
				{
					this._idBatalla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntosUno", DbType="Int NOT NULL")]
		public int puntosUno
		{
			get
			{
				return this._puntosUno;
			}
			set
			{
				if ((this._puntosUno != value))
				{
					this._puntosUno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntosDos", DbType="Int NOT NULL")]
		public int puntosDos
		{
			get
			{
				return this._puntosDos;
			}
			set
			{
				if ((this._puntosDos != value))
				{
					this._puntosDos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotUno", DbType="Int NOT NULL")]
		public int idRobotUno
		{
			get
			{
				return this._idRobotUno;
			}
			set
			{
				if ((this._idRobotUno != value))
				{
					this._idRobotUno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotDos", DbType="Int NOT NULL")]
		public int idRobotDos
		{
			get
			{
				return this._idRobotDos;
			}
			set
			{
				if ((this._idRobotDos != value))
				{
					this._idRobotDos = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblPuntajeLaberinto")]
	public partial class TblPuntajeLaberinto
	{
		
		private int _idRobot;
		
		private System.Nullable<decimal> _timepo1;
		
		private System.Nullable<decimal> _tiempo2;
		
		private System.Nullable<decimal> _tiempo3;
		
		public TblPuntajeLaberinto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timepo1", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> timepo1
		{
			get
			{
				return this._timepo1;
			}
			set
			{
				if ((this._timepo1 != value))
				{
					this._timepo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo2", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> tiempo2
		{
			get
			{
				return this._tiempo2;
			}
			set
			{
				if ((this._tiempo2 != value))
				{
					this._tiempo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiempo3", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> tiempo3
		{
			get
			{
				return this._tiempo3;
			}
			set
			{
				if ((this._tiempo3 != value))
				{
					this._tiempo3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblPuntajeDrone")]
	public partial class TblPuntajeDrone
	{
		
		private int _idRobot;
		
		private System.Nullable<decimal> _timepo1;
		
		private int _puntaje;
		
		public TblPuntajeDrone()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timepo1", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> timepo1
		{
			get
			{
				return this._timepo1;
			}
			set
			{
				if ((this._timepo1 != value))
				{
					this._timepo1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntaje", DbType="Int NOT NULL")]
		public int puntaje
		{
			get
			{
				return this._puntaje;
			}
			set
			{
				if ((this._puntaje != value))
				{
					this._puntaje = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblMinisumo")]
	public partial class TblMinisumo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBatalla_minisumo;
		
		private int _idRobotUno;
		
		private int _idRobotDos;
		
		private EntityRef<TblRobot> _TblRobot;
		
		private EntityRef<TblRobot> _TblRobot1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBatalla_minisumoChanging(int value);
    partial void OnidBatalla_minisumoChanged();
    partial void OnidRobotUnoChanging(int value);
    partial void OnidRobotUnoChanged();
    partial void OnidRobotDosChanging(int value);
    partial void OnidRobotDosChanged();
    #endregion
		
		public TblMinisumo()
		{
			this._TblRobot = default(EntityRef<TblRobot>);
			this._TblRobot1 = default(EntityRef<TblRobot>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBatalla_minisumo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBatalla_minisumo
		{
			get
			{
				return this._idBatalla_minisumo;
			}
			set
			{
				if ((this._idBatalla_minisumo != value))
				{
					this.OnidBatalla_minisumoChanging(value);
					this.SendPropertyChanging();
					this._idBatalla_minisumo = value;
					this.SendPropertyChanged("idBatalla_minisumo");
					this.OnidBatalla_minisumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotUno", DbType="Int NOT NULL")]
		public int idRobotUno
		{
			get
			{
				return this._idRobotUno;
			}
			set
			{
				if ((this._idRobotUno != value))
				{
					if (this._TblRobot.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRobotUnoChanging(value);
					this.SendPropertyChanging();
					this._idRobotUno = value;
					this.SendPropertyChanged("idRobotUno");
					this.OnidRobotUnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotDos", DbType="Int NOT NULL")]
		public int idRobotDos
		{
			get
			{
				return this._idRobotDos;
			}
			set
			{
				if ((this._idRobotDos != value))
				{
					if (this._TblRobot1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRobotDosChanging(value);
					this.SendPropertyChanging();
					this._idRobotDos = value;
					this.SendPropertyChanged("idRobotDos");
					this.OnidRobotDosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMinisumo", Storage="_TblRobot", ThisKey="idRobotUno", OtherKey="idRobot", IsForeignKey=true)]
		public TblRobot TblRobot
		{
			get
			{
				return this._TblRobot.Entity;
			}
			set
			{
				TblRobot previousValue = this._TblRobot.Entity;
				if (((previousValue != value) 
							|| (this._TblRobot.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblRobot.Entity = null;
						previousValue.TblMinisumos.Remove(this);
					}
					this._TblRobot.Entity = value;
					if ((value != null))
					{
						value.TblMinisumos.Add(this);
						this._idRobotUno = value.idRobot;
					}
					else
					{
						this._idRobotUno = default(int);
					}
					this.SendPropertyChanged("TblRobot");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMinisumo1", Storage="_TblRobot1", ThisKey="idRobotDos", OtherKey="idRobot", IsForeignKey=true)]
		public TblRobot TblRobot1
		{
			get
			{
				return this._TblRobot1.Entity;
			}
			set
			{
				TblRobot previousValue = this._TblRobot1.Entity;
				if (((previousValue != value) 
							|| (this._TblRobot1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblRobot1.Entity = null;
						previousValue.TblMinisumos1.Remove(this);
					}
					this._TblRobot1.Entity = value;
					if ((value != null))
					{
						value.TblMinisumos1.Add(this);
						this._idRobotDos = value.idRobot;
					}
					else
					{
						this._idRobotDos = default(int);
					}
					this.SendPropertyChanged("TblRobot1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblMegasumo")]
	public partial class TblMegasumo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBatalla_megasumo;
		
		private int _idRobotUno;
		
		private int _idRobotDos;
		
		private EntityRef<TblRobot> _TblRobot;
		
		private EntityRef<TblRobot> _TblRobot1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBatalla_megasumoChanging(int value);
    partial void OnidBatalla_megasumoChanged();
    partial void OnidRobotUnoChanging(int value);
    partial void OnidRobotUnoChanged();
    partial void OnidRobotDosChanging(int value);
    partial void OnidRobotDosChanged();
    #endregion
		
		public TblMegasumo()
		{
			this._TblRobot = default(EntityRef<TblRobot>);
			this._TblRobot1 = default(EntityRef<TblRobot>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBatalla_megasumo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBatalla_megasumo
		{
			get
			{
				return this._idBatalla_megasumo;
			}
			set
			{
				if ((this._idBatalla_megasumo != value))
				{
					this.OnidBatalla_megasumoChanging(value);
					this.SendPropertyChanging();
					this._idBatalla_megasumo = value;
					this.SendPropertyChanged("idBatalla_megasumo");
					this.OnidBatalla_megasumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotUno", DbType="Int NOT NULL")]
		public int idRobotUno
		{
			get
			{
				return this._idRobotUno;
			}
			set
			{
				if ((this._idRobotUno != value))
				{
					if (this._TblRobot.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRobotUnoChanging(value);
					this.SendPropertyChanging();
					this._idRobotUno = value;
					this.SendPropertyChanged("idRobotUno");
					this.OnidRobotUnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotDos", DbType="Int NOT NULL")]
		public int idRobotDos
		{
			get
			{
				return this._idRobotDos;
			}
			set
			{
				if ((this._idRobotDos != value))
				{
					if (this._TblRobot1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRobotDosChanging(value);
					this.SendPropertyChanging();
					this._idRobotDos = value;
					this.SendPropertyChanged("idRobotDos");
					this.OnidRobotDosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMegasumo", Storage="_TblRobot", ThisKey="idRobotUno", OtherKey="idRobot", IsForeignKey=true)]
		public TblRobot TblRobot
		{
			get
			{
				return this._TblRobot.Entity;
			}
			set
			{
				TblRobot previousValue = this._TblRobot.Entity;
				if (((previousValue != value) 
							|| (this._TblRobot.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblRobot.Entity = null;
						previousValue.TblMegasumos.Remove(this);
					}
					this._TblRobot.Entity = value;
					if ((value != null))
					{
						value.TblMegasumos.Add(this);
						this._idRobotUno = value.idRobot;
					}
					else
					{
						this._idRobotUno = default(int);
					}
					this.SendPropertyChanged("TblRobot");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblMegasumo1", Storage="_TblRobot1", ThisKey="idRobotDos", OtherKey="idRobot", IsForeignKey=true)]
		public TblRobot TblRobot1
		{
			get
			{
				return this._TblRobot1.Entity;
			}
			set
			{
				TblRobot previousValue = this._TblRobot1.Entity;
				if (((previousValue != value) 
							|| (this._TblRobot1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblRobot1.Entity = null;
						previousValue.TblMegasumos1.Remove(this);
					}
					this._TblRobot1.Entity = value;
					if ((value != null))
					{
						value.TblMegasumos1.Add(this);
						this._idRobotDos = value.idRobot;
					}
					else
					{
						this._idRobotDos = default(int);
					}
					this.SendPropertyChanged("TblRobot1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblLegosumo")]
	public partial class TblLegosumo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idBatalla_Legosumo;
		
		private int _idRobotUno;
		
		private int _idRobotDos;
		
		private EntityRef<TblRobot> _TblRobot;
		
		private EntityRef<TblRobot> _TblRobot1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidBatalla_LegosumoChanging(int value);
    partial void OnidBatalla_LegosumoChanged();
    partial void OnidRobotUnoChanging(int value);
    partial void OnidRobotUnoChanged();
    partial void OnidRobotDosChanging(int value);
    partial void OnidRobotDosChanged();
    #endregion
		
		public TblLegosumo()
		{
			this._TblRobot = default(EntityRef<TblRobot>);
			this._TblRobot1 = default(EntityRef<TblRobot>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idBatalla_Legosumo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idBatalla_Legosumo
		{
			get
			{
				return this._idBatalla_Legosumo;
			}
			set
			{
				if ((this._idBatalla_Legosumo != value))
				{
					this.OnidBatalla_LegosumoChanging(value);
					this.SendPropertyChanging();
					this._idBatalla_Legosumo = value;
					this.SendPropertyChanged("idBatalla_Legosumo");
					this.OnidBatalla_LegosumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotUno", DbType="Int NOT NULL")]
		public int idRobotUno
		{
			get
			{
				return this._idRobotUno;
			}
			set
			{
				if ((this._idRobotUno != value))
				{
					if (this._TblRobot.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRobotUnoChanging(value);
					this.SendPropertyChanging();
					this._idRobotUno = value;
					this.SendPropertyChanged("idRobotUno");
					this.OnidRobotUnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobotDos", DbType="Int NOT NULL")]
		public int idRobotDos
		{
			get
			{
				return this._idRobotDos;
			}
			set
			{
				if ((this._idRobotDos != value))
				{
					if (this._TblRobot1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidRobotDosChanging(value);
					this.SendPropertyChanging();
					this._idRobotDos = value;
					this.SendPropertyChanged("idRobotDos");
					this.OnidRobotDosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblLegosumo", Storage="_TblRobot", ThisKey="idRobotUno", OtherKey="idRobot", IsForeignKey=true)]
		public TblRobot TblRobot
		{
			get
			{
				return this._TblRobot.Entity;
			}
			set
			{
				TblRobot previousValue = this._TblRobot.Entity;
				if (((previousValue != value) 
							|| (this._TblRobot.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblRobot.Entity = null;
						previousValue.TblLegosumos.Remove(this);
					}
					this._TblRobot.Entity = value;
					if ((value != null))
					{
						value.TblLegosumos.Add(this);
						this._idRobotUno = value.idRobot;
					}
					else
					{
						this._idRobotUno = default(int);
					}
					this.SendPropertyChanged("TblRobot");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblRobot_TblLegosumo1", Storage="_TblRobot1", ThisKey="idRobotDos", OtherKey="idRobot", IsForeignKey=true)]
		public TblRobot TblRobot1
		{
			get
			{
				return this._TblRobot1.Entity;
			}
			set
			{
				TblRobot previousValue = this._TblRobot1.Entity;
				if (((previousValue != value) 
							|| (this._TblRobot1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TblRobot1.Entity = null;
						previousValue.TblLegosumos1.Remove(this);
					}
					this._TblRobot1.Entity = value;
					if ((value != null))
					{
						value.TblLegosumos1.Add(this);
						this._idRobotDos = value.idRobot;
					}
					else
					{
						this._idRobotDos = default(int);
					}
					this.SendPropertyChanged("TblRobot1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblLaberinto")]
	public partial class TblLaberinto
	{
		
		private int _idRobot;
		
		public TblLaberinto()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblEquipo")]
	public partial class TblEquipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEquipo;
		
		private string _nomEquipo;
		
		private string _paisEquipo;
		
		private string _lugarEquipo;
		
		private System.Data.Linq.Binary _imgEquipo;
		
		private EntitySet<TblRobot> _TblRobots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEquipoChanging(int value);
    partial void OnidEquipoChanged();
    partial void OnnomEquipoChanging(string value);
    partial void OnnomEquipoChanged();
    partial void OnpaisEquipoChanging(string value);
    partial void OnpaisEquipoChanged();
    partial void OnlugarEquipoChanging(string value);
    partial void OnlugarEquipoChanged();
    partial void OnimgEquipoChanging(System.Data.Linq.Binary value);
    partial void OnimgEquipoChanged();
    #endregion
		
		public TblEquipo()
		{
			this._TblRobots = new EntitySet<TblRobot>(new Action<TblRobot>(this.attach_TblRobots), new Action<TblRobot>(this.detach_TblRobots));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEquipo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEquipo
		{
			get
			{
				return this._idEquipo;
			}
			set
			{
				if ((this._idEquipo != value))
				{
					this.OnidEquipoChanging(value);
					this.SendPropertyChanging();
					this._idEquipo = value;
					this.SendPropertyChanged("idEquipo");
					this.OnidEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomEquipo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nomEquipo
		{
			get
			{
				return this._nomEquipo;
			}
			set
			{
				if ((this._nomEquipo != value))
				{
					this.OnnomEquipoChanging(value);
					this.SendPropertyChanging();
					this._nomEquipo = value;
					this.SendPropertyChanged("nomEquipo");
					this.OnnomEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paisEquipo", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string paisEquipo
		{
			get
			{
				return this._paisEquipo;
			}
			set
			{
				if ((this._paisEquipo != value))
				{
					this.OnpaisEquipoChanging(value);
					this.SendPropertyChanging();
					this._paisEquipo = value;
					this.SendPropertyChanged("paisEquipo");
					this.OnpaisEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugarEquipo", DbType="VarChar(50)")]
		public string lugarEquipo
		{
			get
			{
				return this._lugarEquipo;
			}
			set
			{
				if ((this._lugarEquipo != value))
				{
					this.OnlugarEquipoChanging(value);
					this.SendPropertyChanging();
					this._lugarEquipo = value;
					this.SendPropertyChanged("lugarEquipo");
					this.OnlugarEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgEquipo", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary imgEquipo
		{
			get
			{
				return this._imgEquipo;
			}
			set
			{
				if ((this._imgEquipo != value))
				{
					this.OnimgEquipoChanging(value);
					this.SendPropertyChanging();
					this._imgEquipo = value;
					this.SendPropertyChanged("imgEquipo");
					this.OnimgEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblEquipo_TblRobot", Storage="_TblRobots", ThisKey="idEquipo", OtherKey="idEquipo")]
		public EntitySet<TblRobot> TblRobots
		{
			get
			{
				return this._TblRobots;
			}
			set
			{
				this._TblRobots.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TblRobots(TblRobot entity)
		{
			this.SendPropertyChanging();
			entity.TblEquipo = this;
		}
		
		private void detach_TblRobots(TblRobot entity)
		{
			this.SendPropertyChanging();
			entity.TblEquipo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblDrone")]
	public partial class TblDrone
	{
		
		private int _idRobot;
		
		public TblDrone()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRobot", DbType="Int NOT NULL")]
		public int idRobot
		{
			get
			{
				return this._idRobot;
			}
			set
			{
				if ((this._idRobot != value))
				{
					this._idRobot = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TblCategoria")]
	public partial class TblCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCat;
		
		private string _nomCat;
		
		private int _tipoCat;
		
		private EntitySet<TblRobot> _TblRobots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCatChanging(int value);
    partial void OnidCatChanged();
    partial void OnnomCatChanging(string value);
    partial void OnnomCatChanged();
    partial void OntipoCatChanging(int value);
    partial void OntipoCatChanged();
    #endregion
		
		public TblCategoria()
		{
			this._TblRobots = new EntitySet<TblRobot>(new Action<TblRobot>(this.attach_TblRobots), new Action<TblRobot>(this.detach_TblRobots));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCat", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCat
		{
			get
			{
				return this._idCat;
			}
			set
			{
				if ((this._idCat != value))
				{
					this.OnidCatChanging(value);
					this.SendPropertyChanging();
					this._idCat = value;
					this.SendPropertyChanged("idCat");
					this.OnidCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomCat", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string nomCat
		{
			get
			{
				return this._nomCat;
			}
			set
			{
				if ((this._nomCat != value))
				{
					this.OnnomCatChanging(value);
					this.SendPropertyChanging();
					this._nomCat = value;
					this.SendPropertyChanged("nomCat");
					this.OnnomCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoCat", DbType="Int NOT NULL")]
		public int tipoCat
		{
			get
			{
				return this._tipoCat;
			}
			set
			{
				if ((this._tipoCat != value))
				{
					this.OntipoCatChanging(value);
					this.SendPropertyChanging();
					this._tipoCat = value;
					this.SendPropertyChanged("tipoCat");
					this.OntipoCatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TblCategoria_TblRobot", Storage="_TblRobots", ThisKey="idCat", OtherKey="idCategoria")]
		public EntitySet<TblRobot> TblRobots
		{
			get
			{
				return this._TblRobots;
			}
			set
			{
				this._TblRobots.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TblRobots(TblRobot entity)
		{
			this.SendPropertyChanging();
			entity.TblCategoria = this;
		}
		
		private void detach_TblRobots(TblRobot entity)
		{
			this.SendPropertyChanging();
			entity.TblCategoria = null;
		}
	}
}
#pragma warning restore 1591
