<?xml version="1.0" encoding="utf-8"?><Database Name="dbRoboMatrixUdla" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=dbRoboMatrixUdla;Integrated Security=True" SettingsObjectName="CapaDatos.Properties.Settings" SettingsPropertyName="dbRoboMatrixUdlaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TbPuntajeSeguidorLego" Member="TbPuntajeSeguidorLegos">
    <Type Name="TbPuntajeSeguidorLego">
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tiempo1" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="tiempo2" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="tiempo3" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="mejorTiempo" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Association Name="TblSeguidorLego_TbPuntajeSeguidorLego" Member="TblSeguidorLego" ThisKey="idBatalla" OtherKey="idBatalla_SeguidorLego" Type="TblSeguidorLego" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblSeguidorLinea" Member="TblSeguidorLineas">
    <Type Name="TblSeguidorLinea">
      <Column Name="idBatalla_SeguidorLinea" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRobot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="TblSeguidorLinea_TblPuntajeSeguidorLinea" Member="TblPuntajeSeguidorLineas" ThisKey="idBatalla_SeguidorLinea" OtherKey="idBatalla" Type="TblPuntajeSeguidorLinea" />
      <Association Name="TblRobot_TblSeguidorLinea" Member="TblRobot" ThisKey="idRobot" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblSeguidorLego" Member="TblSeguidorLegos">
    <Type Name="TblSeguidorLego">
      <Column Name="idBatalla_SeguidorLego" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRobot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="TblSeguidorLego_TbPuntajeSeguidorLego" Member="TbPuntajeSeguidorLegos" ThisKey="idBatalla_SeguidorLego" OtherKey="idBatalla" Type="TbPuntajeSeguidorLego" />
      <Association Name="TblRobot_TblSeguidorLego" Member="TblRobot" ThisKey="idRobot" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblRobot" Member="TblRobots">
    <Type Name="TblRobot">
      <Column Name="idRobot" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nomRobot" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="estadoRobot" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="liderRobot" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="idCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEquipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblRobot_TblSeguidorLinea" Member="TblSeguidorLineas" ThisKey="idRobot" OtherKey="idRobot" Type="TblSeguidorLinea" />
      <Association Name="TblRobot_TblSeguidorLego" Member="TblSeguidorLegos" ThisKey="idRobot" OtherKey="idRobot" Type="TblSeguidorLego" />
      <Association Name="TblRobot_TblResultadosMegasumo" Member="TblResultadosMegasumos" ThisKey="idRobot" OtherKey="idGanador" Type="TblResultadosMegasumo" />
      <Association Name="TblRobot_TblResultadoMinisumo" Member="TblResultadoMinisumos" ThisKey="idRobot" OtherKey="idGanador" Type="TblResultadoMinisumo" />
      <Association Name="TblRobot_TblResultadoLegosumo" Member="TblResultadoLegosumos" ThisKey="idRobot" OtherKey="idGanador" Type="TblResultadoLegosumo" />
      <Association Name="TblRobot_TblMinisumo" Member="TblMinisumos" ThisKey="idRobot" OtherKey="idRobotUno" Type="TblMinisumo" />
      <Association Name="TblRobot_TblMinisumo1" Member="TblMinisumos1" ThisKey="idRobot" OtherKey="idRobotDos" Type="TblMinisumo" />
      <Association Name="TblRobot_TblMegasumo" Member="TblMegasumos" ThisKey="idRobot" OtherKey="idRobotUno" Type="TblMegasumo" />
      <Association Name="TblRobot_TblMegasumo1" Member="TblMegasumos1" ThisKey="idRobot" OtherKey="idRobotDos" Type="TblMegasumo" />
      <Association Name="TblRobot_TblLegosumo" Member="TblLegosumos" ThisKey="idRobot" OtherKey="idRobotUno" Type="TblLegosumo" />
      <Association Name="TblRobot_TblLegosumo1" Member="TblLegosumos1" ThisKey="idRobot" OtherKey="idRobotDos" Type="TblLegosumo" />
      <Association Name="TblRobot_TblLaberinto" Member="TblLaberintos" ThisKey="idRobot" OtherKey="idRobot" Type="TblLaberinto" />
      <Association Name="TblRobot_TblDrone" Member="TblDrones" ThisKey="idRobot" OtherKey="idRobot" Type="TblDrone" />
      <Association Name="TblEquipo_TblRobot" Member="TblEquipo" ThisKey="idEquipo" OtherKey="idEquipo" Type="TblEquipo" IsForeignKey="true" />
      <Association Name="TblCategoria_TblRobot" Member="TblCategoria" ThisKey="idCategoria" OtherKey="idCat" Type="TblCategoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblResultadosMegasumo" Member="TblResultadosMegasumos">
    <Type Name="TblResultadosMegasumo">
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="puntosUno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="puntosDos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGanador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblRobot_TblResultadosMegasumo" Member="TblRobot" ThisKey="idGanador" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
      <Association Name="TblMegasumo_TblResultadosMegasumo" Member="TblMegasumo" ThisKey="idBatalla" OtherKey="idBatalla_megasumo" Type="TblMegasumo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblResultadoMinisumo" Member="TblResultadoMinisumos">
    <Type Name="TblResultadoMinisumo">
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="puntosUno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="puntosDos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGanador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblRobot_TblResultadoMinisumo" Member="TblRobot" ThisKey="idGanador" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
      <Association Name="TblMinisumo_TblResultadoMinisumo" Member="TblMinisumo" ThisKey="idBatalla" OtherKey="idBatalla_minisumo" Type="TblMinisumo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblResultadoLegosumo" Member="TblResultadoLegosumos">
    <Type Name="TblResultadoLegosumo">
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="puntosUno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="puntosDos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGanador" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblRobot_TblResultadoLegosumo" Member="TblRobot" ThisKey="idGanador" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
      <Association Name="TblLegosumo_TblResultadoLegosumo" Member="TblLegosumo" ThisKey="idBatalla" OtherKey="idBatalla_Legosumo" Type="TblLegosumo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblPuntajeSeguidorLinea" Member="TblPuntajeSeguidorLineas">
    <Type Name="TblPuntajeSeguidorLinea">
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tiempo1" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="tiempo2" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="tiempo3" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="mejorTiempo" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Association Name="TblSeguidorLinea_TblPuntajeSeguidorLinea" Member="TblSeguidorLinea" ThisKey="idBatalla" OtherKey="idBatalla_SeguidorLinea" Type="TblSeguidorLinea" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblPuntajeLaberinto" Member="TblPuntajeLaberintos">
    <Type Name="TblPuntajeLaberinto">
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tiempo1" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="tiempo2" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="tiempo3" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="mejorTiempo" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Association Name="TblLaberinto_TblPuntajeLaberinto" Member="TblLaberinto" ThisKey="idBatalla" OtherKey="idBatalla_Laberinto" Type="TblLaberinto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblPuntajeDrones" Member="TblPuntajeDrones">
    <Type Name="TblPuntajeDrone">
      <Column Name="idPuntaje" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idBatalla" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tiempo1" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="puntaje" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblDrone_TblPuntajeDrone" Member="TblDrone" ThisKey="idBatalla" OtherKey="idBatalla_Drones" Type="TblDrone" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblMinisumo" Member="TblMinisumos">
    <Type Name="TblMinisumo">
      <Column Name="idBatalla_minisumo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRobotUno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRobotDos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="TblMinisumo_TblResultadoMinisumo" Member="TblResultadoMinisumos" ThisKey="idBatalla_minisumo" OtherKey="idBatalla" Type="TblResultadoMinisumo" />
      <Association Name="TblRobot_TblMinisumo" Member="TblRobot" ThisKey="idRobotUno" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
      <Association Name="TblRobot_TblMinisumo1" Member="TblRobot1" ThisKey="idRobotDos" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblMegasumo" Member="TblMegasumos">
    <Type Name="TblMegasumo">
      <Column Name="idBatalla_megasumo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRobotUno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRobotDos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="TblMegasumo_TblResultadosMegasumo" Member="TblResultadosMegasumos" ThisKey="idBatalla_megasumo" OtherKey="idBatalla" Type="TblResultadosMegasumo" />
      <Association Name="TblRobot_TblMegasumo" Member="TblRobot" ThisKey="idRobotUno" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
      <Association Name="TblRobot_TblMegasumo1" Member="TblRobot1" ThisKey="idRobotDos" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblLegosumo" Member="TblLegosumos">
    <Type Name="TblLegosumo">
      <Column Name="idBatalla_Legosumo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRobotUno" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idRobotDos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="TblLegosumo_TblResultadoLegosumo" Member="TblResultadoLegosumos" ThisKey="idBatalla_Legosumo" OtherKey="idBatalla" Type="TblResultadoLegosumo" />
      <Association Name="TblRobot_TblLegosumo" Member="TblRobot" ThisKey="idRobotUno" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
      <Association Name="TblRobot_TblLegosumo1" Member="TblRobot1" ThisKey="idRobotDos" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblLaberinto" Member="TblLaberintos">
    <Type Name="TblLaberinto">
      <Column Name="idBatalla_Laberinto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idRobot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Association Name="TblLaberinto_TblPuntajeLaberinto" Member="TblPuntajeLaberintos" ThisKey="idBatalla_Laberinto" OtherKey="idBatalla" Type="TblPuntajeLaberinto" />
      <Association Name="TblRobot_TblLaberinto" Member="TblRobot" ThisKey="idRobot" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblEquipo" Member="TblEquipos">
    <Type Name="TblEquipo">
      <Column Name="idEquipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomEquipo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="paisEquipo" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="lugarEquipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="imgEquipo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="TblEquipo_TblRobot" Member="TblRobots" ThisKey="idEquipo" OtherKey="idEquipo" Type="TblRobot" />
    </Type>
  </Table>
  <Table Name="dbo.TblDrones" Member="TblDrones">
    <Type Name="TblDrone">
      <Column Name="estado" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="idRobot" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idBatalla_Drones" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="TblDrone_TblPuntajeDrone" Member="TblPuntajeDrones" ThisKey="idBatalla_Drones" OtherKey="idBatalla" Type="TblPuntajeDrone" />
      <Association Name="TblRobot_TblDrone" Member="TblRobot" ThisKey="idRobot" OtherKey="idRobot" Type="TblRobot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TblCategoria" Member="TblCategorias">
    <Type Name="TblCategoria">
      <Column Name="idCat" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nomCat" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="tipoCat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TblCategoria_TblRobot" Member="TblRobots" ThisKey="idCat" OtherKey="idCategoria" Type="TblRobot" />
    </Type>
  </Table>
</Database>